version: '3.1'

services:
  docker-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring_db
    volumes:
      - .:/docker-entrypoint-initdb.d
  spring-boot-mysql-docker-webapp:
    build: .
    depends_on:
      - docker-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=spring_db
      - DATABASE_PORT=3306